"""Sprint 05 Epic O — wiki exporter (zero network; publish() is exercised against a LOCAL
bare git repo, exactly the shape of <repo>.wiki.git)."""

import subprocess
from pathlib import Path

import pytest

from synapse.wiki import _to_wiki_dialect, export, publish

FIXTURES = Path(__file__).resolve().parent / "fixtures"


@pytest.fixture
def vault(tmp_path):
    from modules.graph.src.services import GraphService
    from modules.ingest.src.services import IngestService
    v = tmp_path / "vault"
    IngestService(v, frozenset({".git", "node_modules"})).ingest(
        [FIXTURES / "repo_a", FIXTURES / "repo_b"])
    GraphService(v).rebuild()
    return v


class TestDialect:
    def test_wikilinks_resolve_and_lose_md_suffix(self):
        assert _to_wiki_dialect("See [[repo_a__docs__alpha.md]] now") == \
            "See [[repo_a__docs__alpha|repo_a__docs__alpha]] now"
        assert _to_wiki_dialect("[[a.md|label]]") == "[[label|a]]"           # label|page order
        assert _to_wiki_dialect("[[Ghost Concept]]") == "[[Ghost Concept]]"  # unresolved → create-link

    def test_export_pages_home_sidebar_banner(self, vault, tmp_path):
        out = tmp_path / "wiki"
        counts = export(vault, out)
        assert counts["pages"] == counts["notes"] == 4
        page = (out / "repo_a__docs__alpha").with_suffix(".md").read_text(encoding="utf-8")
        assert page.startswith("> 🧠 _Generated by [SYNAPSE]")          # the don't-edit banner
        assert "[[Beta|repo_b__beta]]" in page          # human-form link RESOLVED to its page
        assert "_Source: `repo_a/docs/alpha.md`_" in page               # provenance footer
        assert "synapse.content_hash" not in page                       # frontmatter stripped
        home = (out / "Home.md").read_text(encoding="utf-8")
        assert "front door" in home
        side = (out / "_Sidebar.md").read_text(encoding="utf-8")
        assert "[[Home]]" in side and "4 notes" in side


class TestPublish:
    def test_publish_to_local_bare_repo_and_noop_second_run(self, vault, tmp_path):
        bare = tmp_path / "site.wiki.git"
        subprocess.run(["git", "init", "-q", "--bare", str(bare)], check=True)
        # a bare repo with zero commits can't be shallow-cloned with content; seed one page
        seed = tmp_path / "seed"
        subprocess.run(["git", "clone", "-q", str(bare), str(seed)], check=True)
        (seed / "Home.md").write_text("first page\n", encoding="utf-8")
        subprocess.run(["git", "add", "-A"], cwd=seed, check=True)
        subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", "seed"],
                       cwd=seed, check=True)
        subprocess.run(["git", "push", "-q"], cwd=seed, check=True)

        out = publish(vault, str(bare), tmp_path / "w1")
        assert out["pushed"] is True and out["pages"] == 4
        again = publish(vault, str(bare), tmp_path / "w2")
        assert again["pushed"] is False                     # honest no-op when unchanged

    def test_publish_missing_wiki_repo_fails_actionably(self, vault, tmp_path):
        with pytest.raises(RuntimeError, match="first page"):
            publish(vault, str(tmp_path / "nope.wiki.git"), tmp_path / "w3")
