"""
Publish the brain as a GitHub Wiki (sprint 05, Epic O) — dogfood: don't write a wiki,
export the vault AS the wiki. GitHub wikis are git repos of markdown with `[[wikilink]]`
support — exactly the vault's format, modulo a small dialect transform.

    python -m synapse.wiki export <outdir>     # transform the vault into wiki pages
    python -m synapse.wiki publish [repo-url]  # export + push to <repo>.wiki.git

Dialect: GitHub resolves `[[Page Name]]` to the file `Page-Name.md` (case-insensitive,
spaces↔dashes) — so wikilinks must lose their `.md` suffix, and page filenames must not
contain `/`. Our note ids are already flat (`repo__path__file.md`) — perfect fit.
`Index.md` becomes `Home.md`; a `_Sidebar.md` lists the most-connected notes.

The wiki is a DERIVED surface (same doctrine as graph.json): every page carries a banner
pointing at the source; edits belong in the source repos, never here.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_BACKEND = Path(__file__).resolve().parents[1]
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

BANNER = ("> 🧠 _Generated by [SYNAPSE](https://github.com/SynaptixLabs/Synapse) from this "
          "repository's own markdown — **don't edit here**, edit the source file and the "
          "next publish refreshes this page._\n\n")

_WIKILINK_RE = re.compile(r"\[\[([^\[\]|#]+?)(#[^\[\]|]*)?(?:\|([^\[\]]*))?\]\]")
_MDLINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+?\.md)(?:#[^)]*)?\)")


def _page_name(note_id: str) -> str:
    return note_id.removesuffix(".md")


def _to_wiki_dialect(body: str, note: dict | None = None, resolver=None) -> str:
    """Rewrite links for GitHub's dialect, RESOLVING them exactly like the graph does:
    vault bodies carry source-form links (`[[Beta]]`, `[the readme](../README.md)`) whose
    targets only the namespace knows. Resolved → `[[display|page-name]]`; unresolved →
    left as-is (GitHub renders them as create-links — the wiki's own ghost notes)."""
    def wl(m):
        target, label = m.group(1).strip(), m.group(3)
        display = label or _page_name(target)
        if resolver:
            hit = resolver("wikilink", target)
        else:   # no namespace (unit shortcut): treat an exact `.md` id as its own page
            hit = target if target.lower().endswith(".md") else None
        return f"[[{display}|{_page_name(hit)}]]" if hit else f"[[{display}]]"
    def ml(m):
        label, target = m.group(1), m.group(2)
        hit = resolver("relative", target) if (resolver and note is not None) else None
        return f"[[{label or target}|{_page_name(hit)}]]" if hit else m.group(0)
    return _MDLINK_RE.sub(ml, _WIKILINK_RE.sub(wl, body))


def export(vault_path: Path, outdir: Path) -> dict:
    """Vault → wiki pages in `outdir`. Returns honest counts."""
    from modules.graph.src.services import GraphService

    svc = GraphService(vault_path)
    g = svc.build()
    notes = svc._load_notes()
    exact, stems = GraphService._namespace(notes)   # the graph's own resolution rules
    by_id = {n["id"]: n for n in notes}

    def make_resolver(note: dict | None):
        def resolve(kind: str, target: str) -> str | None:
            if kind == "wikilink":
                return svc._resolve_wikilink(target, exact, stems)
            if kind == "relative" and note is not None:
                return GraphService._resolve_relative(note, target, exact)
            return None
        return resolve

    outdir.mkdir(parents=True, exist_ok=True)
    pages = 0
    for note_path in sorted(svc.notes_dir.glob("*.md")):
        text = note_path.read_text(encoding="utf-8", errors="replace")
        # frontmatter → a small provenance footer (GitHub renders frontmatter as a table,
        # which reads as clutter on a wiki page)
        fm = re.match(r"\A---\n(.*?)\n---\n", text, re.DOTALL)
        body = text[fm.end():] if fm else text
        src_line = ""
        if fm:
            fields = dict(re.findall(r"^synapse\.(source_repo|source_path): (.+)$", fm.group(1), re.MULTILINE))
            if fields.get("source_path"):
                src_line = f"\n\n---\n_Source: `{fields.get('source_repo', '')}/{fields['source_path']}`_\n"
        note_meta = by_id.get(note_path.name)
        (outdir / f"{_page_name(note_path.name)}.md").write_text(
            BANNER + _to_wiki_dialect(body, note_meta, make_resolver(note_meta)) + src_line,
            encoding="utf-8")
        pages += 1
    # Home = the Index (the brain's front door)
    index = svc.read_index()
    if index:
        (outdir / "Home.md").write_text(
            BANNER + _to_wiki_dialect(index, None, make_resolver(None)), encoding="utf-8")
    # Sidebar: top-connected notes
    stats = g.stats()
    side = ["### 🧠 The brain", "", "[[Home]]", "", "**Most connected**", ""]
    side += [f"- [[{_page_name(t['id'])}]]" for t in stats["top_connected"]]
    side += ["", f"_{stats['notes']} notes · {stats['edges_total']} edges_"]
    (outdir / "_Sidebar.md").write_text("\n".join(side) + "\n", encoding="utf-8")
    return {"pages": pages, "notes": stats["notes"], "edges": stats["edges_total"]}


def publish(vault_path: Path, repo_url: str, workdir: Path) -> dict:
    """Export + push one snapshot commit to the wiki git repo (plain push — wiki history
    accumulates one commit per publish; it's derived content, so that history is noise but
    harmless). A rejected push (e.g. someone edited the wiki by hand) surfaces as an
    actionable error rather than a stack trace."""
    clone = workdir / "wiki-checkout"
    r = subprocess.run(["git", "clone", "--depth", "1", repo_url, str(clone)],
                       capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        raise RuntimeError(
            f"Cannot clone {repo_url} — GitHub creates the wiki repo only after the wiki "
            f"is enabled and has a first page (repo → Wiki → Create). Details: {r.stderr.strip()[:300]}")
    for old in clone.glob("*.md"):
        old.unlink()
    counts = export(vault_path, clone)
    subprocess.run(["git", "add", "-A"], cwd=clone, check=True)
    diff = subprocess.run(["git", "diff", "--cached", "--quiet"], cwd=clone)
    if diff.returncode == 0:
        return {**counts, "pushed": False, "message": "wiki already up to date"}
    subprocess.run(["git", "-c", "user.name=synapse-wiki-publish",
                    "-c", "user.email=noreply@synaptixlabs.ai",
                    "commit", "-q", "-m", "publish: brain snapshot (generated by SYNAPSE)"],
                   cwd=clone, check=True)
    r = subprocess.run(["git", "push", "-q"], cwd=clone, capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        raise RuntimeError(
            "Push rejected — the wiki changed since this export (someone edited it by hand?). "
            f"Re-run to publish on top of the new state. Details: {r.stderr.strip()[:300]}")
    return {**counts, "pushed": True}


def main(argv: list[str] | None = None) -> int:
    import argparse
    import tempfile

    from app.core.config import load_settings
    p = argparse.ArgumentParser(prog="synapse.wiki", description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)
    e = sub.add_parser("export"); e.add_argument("outdir")
    pub = sub.add_parser("publish")
    pub.add_argument("repo_url", nargs="?",
                     default="https://github.com/SynaptixLabs/Synapse.wiki.git")
    args = p.parse_args(argv)
    settings = load_settings()
    if args.cmd == "export":
        counts = export(settings.vault_path, Path(args.outdir))
        print(f"exported {counts['pages']} pages ({counts['notes']} notes, {counts['edges']} edges) → {args.outdir}")
        return 0
    with tempfile.TemporaryDirectory() as td:
        out = publish(settings.vault_path, args.repo_url, Path(td))
        print(f"{'pushed' if out.get('pushed') else out.get('message', 'no-op')}: "
              f"{out['pages']} pages ({out['notes']} notes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
